module.exports = {
  TechnologySidebar: {
    'About the ZKVM': [{type: 'autogenerated', dirName: 'explainers/zkvm'}],
    'About the Proof System': [{type: 'autogenerated', dirName: 'explainers/proof-system'}],
    'Reference Docs': [{type: 'autogenerated', dirName: 'reference-docs'},],    
  },
  BuildSidebar: {
    
  },

  GettingStartedSidebar: [
    { type: 'category',
      label: '"Hello, Multiply!"',
      items: [
        {
          type: 'doc',
          label: '"Hello, Multiply!" Tutorial',
          id: 'examples/hello_multiply',
        },
        {
          type: 'doc',
          label: 'Understanding "Hello, Multiply!"',
          id: 'examples/understanding-hello-multiply',
        },
        {
          type: 'link',
          label: '"Hello, Multiply!" Source',
          href: 'https://github.com/risc0/risc0-rust-examples/tree/main/factors',
        },
      ]
    },
    { type: 'category',
      label: 'RISC Zero Starter Template',
      items: [
        {
          type: 'doc',
          label: 'Understanding the Starter Template',
          id: 'examples/understanding_template',
        },
        {
          type: 'link',
          label: 'Starter Template Source',
          href: 'https://github.com/risc0/risc0-rust-starter',
        }
      ]
    },
    { type: 'category',
      label: 'Battleship',
      items: [
        {
          type: 'doc',
          label: 'Battleship Explainer',
          id: 'examples/battleship_rust',
        },
        {
          type: 'link',
          label: 'Battleship Source',
          href: 'https://github.com/risc0/battleship-example',
        }
      ]
    },
    { type: 'category',
      label: 'Digital Signatures',
      items: [
        {
          type: 'doc',
          label: 'Digital Signatures Explainer',
          id: 'examples/digital_signatures',
        },
        {
          type: 'link',
          label: 'Digital Signatures Source',
          href: 'https://github.com/risc0/risc0-rust-examples/tree/main/digital-signature',
        }
      ]
    },
    { type: 'category',
    label: 'Password Validity Checker',
    items: [
      {
        type: 'doc',
        label: 'Understanding the Password Validity Checker',
        id: 'examples/password_checker',
      },
      {
        type: 'link',
        label: 'Password Validity Checker Source',
        href: 'https://github.com/risc0/risc0-rust-examples/tree/main/password-checker',
      }
    ]
  },
    { 
      type: 'link',
      label: 'RISC Zero Rust Crates',
      href: 'https://github.com/risc0/risc0#rust-crates',
    },
    { type: 'link',
      label: 'Contribute to RISC Zero',
      href: 'https://github.com/risc0/risc0',
    }, 

  ]
};
