module.exports = {
  ProofSystemSidebar: {
    'About the Proof System': [{type: 'autogenerated', dirName: 'explainers/proof-system'}, {
      type: 'link',
      label: 'Fibonacci Trace Validation', // The link label
      href: 'https://docs.google.com/spreadsheets/d/e/2PACX-1vSJ1J5PcS2op_vrGtbK5Mif0gAN6wbAaTSWTHy2vuFtfbtqbI_dRqpalNamNjjUcyqD7hDPJRgI2cG-/pubhtml#', // The external URL
    },],
  },

  zkVMSidebar: {
    'About the zkVM': [{type: 'autogenerated', dirName: 'explainers/zkvm'}],
  },

  ReferenceSidebar: {
    'Reference': [{type: 'autogenerated', dirName: 'reference-docs'}],
  },

  TechnologySidebar: {
    'About the ZKVM': [{type: 'autogenerated', dirName: 'explainers/zkvm'}],
    'About the Proof System': [{type: 'autogenerated', dirName: 'explainers/proof-system'}],
    'Reference Docs': [{type: 'autogenerated', dirName: 'reference-docs'},],
    
  },

  };
