module.exports = {
  TechnologySidebar: {
    'About the ZKVM': [{type: 'autogenerated', dirName: 'explainers/zkvm'}],
    'About the Proof System': [{type: 'autogenerated', dirName: 'explainers/proof-system'}],
    'Reference Docs': [{type: 'autogenerated', dirName: 'reference-docs'},],    
  },
  BuildSidebar: {
    
  },

  GettingStartedSidebar: [
    { type: 'link',
      label: 'Hello World in Rust',
      href: 'https://github.com/risc0/risc0-rust-starter',
    },
    { type: 'link',
      label: 'RISC Zero Battleship',
      href: 'https://github.com/risc0/battleship-example',
    },
    { type: 'link',
      label: 'RISC Zero Rust Crates',
      href: 'https://github.com/risc0/risc0#rust-crates',
    },
    { type: 'link',
      label: 'Contribute to RISC Zero',
      href: 'https://github.com/risc0/risc0',
    } 
  ],
};
